language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/newsletter-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - stage: production
      name: asumag
      script: npx @base-cms/newsletter-deployment-tool deploy asumag gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: contractingbusiness
      script: npx @base-cms/newsletter-deployment-tool deploy contractingbusiness gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: contractormag
      script: npx @base-cms/newsletter-deployment-tool deploy contractormag gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: ecmweb
      script: npx @base-cms/newsletter-deployment-tool deploy ecmweb gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: ewweb
      script: npx @base-cms/newsletter-deployment-tool deploy ewweb gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: hpac
      script: npx @base-cms/newsletter-deployment-tool deploy hpac gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: tdworld
      script: npx @base-cms/newsletter-deployment-tool deploy tdworld gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: vspc
      script: npx @base-cms/newsletter-deployment-tool deploy vspc picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: rermag
      script: npx @base-cms/newsletter-deployment-tool deploy rermag gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: electricalmarketing
      script: npx @base-cms/newsletter-deployment-tool deploy electricalmarketing gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: trucker
      script: npx @base-cms/newsletter-deployment-tool deploy trucker gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: electronicdesign
      script: npx @base-cms/newsletter-deployment-tool deploy electronicdesign gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: fleetowner
      script: npx @base-cms/newsletter-deployment-tool deploy fleetowner gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: hydraulicspneumatics
      script: npx @base-cms/newsletter-deployment-tool deploy hydraulicspneumatics gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: mwrf
      script: npx @base-cms/newsletter-deployment-tool deploy mwrf gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: newequipment
      script: npx @base-cms/newsletter-deployment-tool deploy newequipment gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: sourcetoday
      script: npx @base-cms/newsletter-deployment-tool deploy sourcetoday gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: machinedesign
      script: npx @base-cms/newsletter-deployment-tool deploy machinedesign gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: industryweek
      script: npx @base-cms/newsletter-deployment-tool deploy industryweek gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: trailerbodybuilders
      script: npx @base-cms/newsletter-deployment-tool deploy trailerbodybuilders gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: ehstoday
      script: npx @base-cms/newsletter-deployment-tool deploy ehstoday gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: bulktransporter
      script: npx @base-cms/newsletter-deployment-tool deploy bulktransporter gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: refrigeratedtransporter
      script: npx @base-cms/newsletter-deployment-tool deploy refrigeratedtransporter gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: mhlnews
      script: npx @base-cms/newsletter-deployment-tool deploy mhlnews gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: forgingmagazine
      script: npx @base-cms/newsletter-deployment-tool deploy forgingmagazine gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: foundrymag
      script: npx @base-cms/newsletter-deployment-tool deploy foundrymag gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: americanmachinist
      script: npx @base-cms/newsletter-deployment-tool deploy americanmachinist gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: powerelectronics
      script: npx @base-cms/newsletter-deployment-tool deploy powerelectronics gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: smartbuildingstech
      script: npx @base-cms/newsletter-deployment-tool deploy smartbuildingstech gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: energytech
      script: npx @base-cms/newsletter-deployment-tool deploy energytech gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    #############################
    #       Picon Below         #
    #############################

    - stage: production
      name: distributedenergy
      script: npx @base-cms/newsletter-deployment-tool deploy distributedenergy picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: processingmagazine
      script: npx @base-cms/newsletter-deployment-tool deploy processingmagazine picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: hpnonline
      script: npx @base-cms/newsletter-deployment-tool deploy hpnonline picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: mlo-online
      script: npx @base-cms/newsletter-deployment-tool deploy mlo-online picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: piprocessinstrumentation
      script: npx @base-cms/newsletter-deployment-tool deploy piprocessinstrumentation picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: evaluationengineering
      script: npx @base-cms/newsletter-deployment-tool deploy evaluationengineering picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: gxcontractor
      script: npx @base-cms/newsletter-deployment-tool deploy gxcontractor picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: plasticsmachinerymanufacturing
      script: npx @base-cms/newsletter-deployment-tool deploy plasticsmachinerymanufacturing picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: fleetmaintenance
      script: npx @base-cms/newsletter-deployment-tool deploy fleetmaintenance picon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    #############################
    #       Aerilon Below         #
    #############################

    - stage: production
      name: dentaleconomics
      script: npx @base-cms/newsletter-deployment-tool deploy dentaleconomics aerilon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: production
      name: rdhmag
      script: npx @base-cms/newsletter-deployment-tool deploy rdhmag aerilon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/newsletter-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]
