version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  entrypoint: ["node_modules/.bin/basecms-newsletters"]
  command: ["dev", "index.js"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}


x-env-aerilon: &env-aerilon
  GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}

x-env-gemenon: &env-gemenon
  GRAPHQL_URI: ${GRAPHQL_URI-https://gemenon.graphql.base-cms.io}

x-env-picon: &env-picon
  GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  ecmweb:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ecmweb
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19400
      LIVERELOAD_PORT: 29400
      TENANT_KEY: ebm_ecmweb
    ports:
      - "19400:80"
      - "29400:29400"

  tdworld:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/tdworld
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19401
      LIVERELOAD_PORT: 29401
      TENANT_KEY: ebm_tdworld
    ports:
      - "19401:80"
      - "29401:29401"

  ewweb:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ewweb
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19402
      LIVERELOAD_PORT: 29402
      TENANT_KEY: ebm_ewweb
    ports:
      - "19402:80"
      - "29402:29402"

  rermag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/rermag
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19403
      LIVERELOAD_PORT: 29403
      TENANT_KEY: ebm_rermag
    ports:
      - "19403:80"
      - "29403:29403"

  contractormag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/contractormag
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19404
      LIVERELOAD_PORT: 29404
      TENANT_KEY: ebm_contractormag
    ports:
      - "19404:80"
      - "29404:29404"

  hpac:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/hpac
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19405
      LIVERELOAD_PORT: 29405
      TENANT_KEY: ebm_hpac
    ports:
      - "19405:80"
      - "29405:29405"

  vspc:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/vspc
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19406
      LIVERELOAD_PORT: 29406
      TENANT_KEY: cygnus_vspc
    ports:
      - "19406:80"
      - "29406:29406"

  asumag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/asumag
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19407
      LIVERELOAD_PORT: 29407
      TENANT_KEY: ebm_asumag
    ports:
      - "19407:80"
      - "29407:29407"

  contractingbusiness:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/contractingbusiness
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19408
      LIVERELOAD_PORT: 29408
      TENANT_KEY: ebm_contractingbusiness
    ports:
      - "19408:80"
      - "29408:29408"

  electricalmarketing:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/electricalmarketing
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19409
      LIVERELOAD_PORT: 29409
      TENANT_KEY: ebm_electricalmarketing
    ports:
      - "19409:80"
      - "29409:29409"

  trucker:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/trucker
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19410
      LIVERELOAD_PORT: 29410
      TENANT_KEY: ebm_trucker
    ports:
      - "19410:80"
      - "29410:29410"

  electronicdesign:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/electronicdesign
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19411
      LIVERELOAD_PORT: 29411
      TENANT_KEY: ebm_electronicdesign
    ports:
      - "19411:80"
      - "29411:29411"

  fleetowner:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/fleetowner
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19412
      LIVERELOAD_PORT: 29412
      TENANT_KEY: ebm_fleetowner
    ports:
      - "19412:80"
      - "29412:29412"

  hydraulicspneumatics:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/hydraulicspneumatics
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19413
      LIVERELOAD_PORT: 29413
      TENANT_KEY: ebm_hydraulicspneumatics
    ports:
      - "19413:80"
      - "29413:29413"

  mwrf:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/mwrf
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19414
      LIVERELOAD_PORT: 29414
      TENANT_KEY: ebm_mwrf
    ports:
      - "19414:80"
      - "29414:29414"

  newequipment:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/newequipment
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19415
      LIVERELOAD_PORT: 29415
      TENANT_KEY: ebm_newequipment
    ports:
      - "19415:80"
      - "29415:29415"

  sourcetoday:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/sourcetoday
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19416
      LIVERELOAD_PORT: 29416
      TENANT_KEY: ebm_sourcetoday
    ports:
      - "19416:80"
      - "29416:29416"

  machinedesign:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/machinedesign
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19417
      LIVERELOAD_PORT: 29417
      TENANT_KEY: ebm_machinedesign
    ports:
      - "19417:80"
      - "29417:29417"

  industryweek:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/industryweek
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19418
      LIVERELOAD_PORT: 29418
      TENANT_KEY: ebm_industryweek
    ports:
      - "19418:80"
      - "29418:29418"

  trailerbodybuilders:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/trailerbodybuilders
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19419
      LIVERELOAD_PORT: 29419
      TENANT_KEY: ebm_trailerbodybuilders
    ports:
      - "19419:80"
      - "29419:29419"

  ehstoday:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ehstoday
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19420
      LIVERELOAD_PORT: 29420
      TENANT_KEY: ebm_ehstoday
    ports:
      - "19420:80"
      - "29420:29420"

  bulktransporter:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/bulktransporter
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19421
      LIVERELOAD_PORT: 29421
      TENANT_KEY: ebm_bulktransporter
    ports:
      - "19421:80"
      - "29421:29421"

  refrigeratedtransporter:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/refrigeratedtransporter
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19422
      LIVERELOAD_PORT: 29422
      TENANT_KEY: ebm_refrigeratedtransporter
    ports:
      - "19422:80"
      - "29422:29422"

  mhlnews:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/mhlnews
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19423
      LIVERELOAD_PORT: 29423
      TENANT_KEY: ebm_mhlnews
    ports:
      - "19423:80"
      - "29423:29423"

  forgingmagazine:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/forgingmagazine
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19424
      LIVERELOAD_PORT: 29424
      TENANT_KEY: ebm_forgingmagazine
    ports:
      - "19424:80"
      - "29424:29424"

  foundrymag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/foundrymag
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19425
      LIVERELOAD_PORT: 29425
      TENANT_KEY: ebm_foundrymag
    ports:
      - "19425:80"
      - "29425:29425"

  americanmachinist:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/americanmachinist
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19426
      LIVERELOAD_PORT: 29426
      TENANT_KEY: ebm_americanmachinist
    ports:
      - "19426:80"
      - "29426:29426"

  powerelectronics:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/powerelectronics
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19427
      LIVERELOAD_PORT: 29427
      TENANT_KEY: ebm_powerelectronics
    ports:
      - "19427:80"
      - "29427:29427"

  distributedenergy:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/distributedenergy
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19428
      LIVERELOAD_PORT: 29428
      TENANT_KEY: ebm_dte
    ports:
      - "19428:80"
      - "29428:29428"

  processingmagazine:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/processingmagazine
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19429
      LIVERELOAD_PORT: 29429
      TENANT_KEY: ebm_pcm
    ports:
      - "19429:80"
      - "29429:29429"

  hpnonline:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/hpnonline
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19430
      LIVERELOAD_PORT: 29430
      TENANT_KEY: ebm_hpn
    ports:
      - "19430:80"
      - "29430:29430"

  mlo-online:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/mlo-online
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19431
      LIVERELOAD_PORT: 29431
      TENANT_KEY: ebm_mlo
    ports:
      - "19431:80"
      - "29431:29431"

  piprocessinstrumentation:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/piprocessinstrumentation
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19432
      LIVERELOAD_PORT: 29432
      TENANT_KEY: ebm_fcn
    ports:
      - "19432:80"
      - "29432:29432"

  dentaleconomics:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/dentaleconomics
    environment:
      <<: *env
      <<: *env-aerilon
      PORT: 80
      EXPOSED_PORT: 19433
      LIVERELOAD_PORT: 29433
      TENANT_KEY: ebm_de
    ports:
      - "19433:80"
      - "29433:29433"

  evaluationengineering:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/evaluationengineering
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19434
      LIVERELOAD_PORT: 29434
      TENANT_KEY: ebm_ee
    ports:
      - "19434:80"
      - "29434:29434"

  rdhmag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/rdhmag
    environment:
      <<: *env
      <<: *env-aerilon
      PORT: 80
      EXPOSED_PORT: 19435
      LIVERELOAD_PORT: 29435
      TENANT_KEY: ebm_rdh
    ports:
      - "19435:80"
      - "29435:29435"

  gxcontractor:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/gxcontractor
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19436
      LIVERELOAD_PORT: 29436
      TENANT_KEY: ebm_gxc
    ports:
      - "19436:80"
      - "29436:29436"

  plasticsmachinerymanufacturing:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/plasticsmachinerymanufacturing
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19437
      LIVERELOAD_PORT: 29437
      TENANT_KEY: ebm_pmm
    ports:
      - "19437:80"
      - "29437:29437"

  fleetmaintenance:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/fleetmaintenance
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19438
      LIVERELOAD_PORT: 29438
      TENANT_KEY: ebm_fm
    ports:
      - "19438:80"
      - "29438:29438"

  smartbuildingstech:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/smartbuildingstech
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19439
      LIVERELOAD_PORT: 29439
      TENANT_KEY: ebm_smartbuildingstech
    ports:
      - "19439:80"
      - "29439:29439"

  energytech:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/energytech
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19439
      LIVERELOAD_PORT: 29439
      TENANT_KEY: ebm_energytech
    ports:
      - "19439:80"
      - "29439:29439"

volumes:
  yarn-cache: {}
